In [1]:
import pandas as pd
import numpy as np

In [2]:
PATH_FILE = "/home/gustavo/repos/pandas_specialization/data/customer_segmentation_mixed.csv"

df = pd.read_csv(PATH_FILE)

In [3]:
df.head(3)

,Age,Annual_Income,Spending_Score,Monthly_Visits,Gender,Preferred_Product
0,56,26102,85,6,Female,Clothing
1,46,70336,75,18,Male,Home
2,32,105314,36,10,Male,Groceries

In [4]:
df.groupby("Preferred_Product")["Monthly_Visits"].mean()

Preferred_Product
Clothing        9.416667
Electronics     8.925373
Groceries       9.836066
Home            9.268657
Sports         10.072289
Name: Monthly_Visits, dtype: float64

In [5]:
df.pivot_table(values="Monthly_Visits", index="Preferred_Product")

                   Monthly_Visits
Preferred_Product
Clothing                 9.416667
Electronics              8.925373
Groceries                9.836066
Home                     9.268657
Sports                  10.072289

In [9]:
df.pivot_table(values="Monthly_Visits", index="Preferred_Product", aggfunc="median")

                   Monthly_Visits
Preferred_Product
Clothing                      9.0
Electronics                   8.0
Groceries                    10.0
Home                          8.0
Sports                       10.0